events {
    worker_connections 1024;
}

http {
    log_format detailed '$remote_addr - [$time_local] "$request" '
                       '$status $body_bytes_sent '
                       '"$http_user_agent" '
                       'upstream: $upstream_addr '
                       'response_time: $upstream_response_time';

    access_log /var/log/nginx/access.log detailed;
    error_log /var/log/nginx/error.log warn;


    upstream frontend_app {
        server frontend:80;
    }

    upstream python_backend {
        server web1:5000; 
    }

    upstream node_backend {
        server web2:3000; 
    }

    upstream go_backend {
        server web3:8080;
    }

    server {
        listen 80;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        location / {
            proxy_pass http://frontend_app;
            access_log /var/log/nginx/frontend.log detailed;
        }

        location /scoreboard {
            proxy_pass http://frontend_app;
            access_log /var/log/nginx/scoreboard.log detailed;
        }

        location /api/login {
            proxy_pass http://node_backend;
            access_log /var/log/nginx/node.log detailed;
        }

        location /api/vote {
            proxy_pass http://node_backend;
            access_log /var/log/nginx/node.log detailed;
        }

        location /api/skor {
            proxy_pass http://python_backend;
            access_log /var/log/nginx/python.log detailed;
        }

        location /admin {
            proxy_pass http://frontend_app;
            access_log /var/log/nginx/admin_frontend.log detailed;
        }

        location /api/admin/data {
            proxy_pass http://go_backend;
            access_log /var/log/nginx/go.log detailed;
        }

        location = /admin {
            return 301 /admin/;
        }
    }
}